stages:
  - build
  - deploy

variables:
  REGISTRY: "192.168.1.31:5050"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"

.build_template: &build_template
  stage: build
  image: docker:24
  services:
    - name: docker:24-dind
      command: ["--insecure-registry", "192.168.1.31:5050"]
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY
  script:
    - |
      IMAGE="$REGISTRY/root/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA"
      IMAGE_LATEST="$REGISTRY/root/$SERVICE_NAME:latest"
      docker build -t $IMAGE -t $IMAGE_LATEST ./core/$SERVICE_NAME
      docker push $IMAGE
      docker push $IMAGE_LATEST
  only:
    - main

build:api-gateway:
  <<: *build_template
  variables:
    SERVICE_NAME: api-gateway

build:auth-service:
  <<: *build_template
  variables:
    SERVICE_NAME: auth-services

build:operator-service:
  <<: *build_template
  variables:
    SERVICE_NAME: operator-service

build:storage-service:
  <<: *build_template
  variables:
    SERVICE_NAME: storage-service

build:user-service:
  <<: *build_template
  variables:
    SERVICE_NAME: user-service