export const API_URL = import.meta.env.VITE_API_URL
export const BASE_URL = import.meta.env.VITE_BASE_URL
export const LOGIN_URL = BASE_URL + "/auth/login";
export const REGISTER_URL = BASE_URL + "/auth/register";
export const DOCS_URL = BASE_URL + "/docs";
export const HOMEPAGE_URL = BASE_URL;
export const ADMIN_ROLE = "admin";
export const USER_ROLE = "user";
export const SSE_URL = "";
export const WS_SERVER_URL = "wss://hoscopus.wfdnstore.online";
export const OAUTH_URL_GITHUB = "https://api.wfdnstore.online/api/v1/auth/github"
