apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: workspaces
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: 192.168.1.10:5050/root/workspaces/auth-service:latest
          ports:
            - containerPort: 5051
          env:
            - name: PORT
              value: "5051"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: JWT_SECRET
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: DB_URL