apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      app: {{.Name}}
  template:
    metadata:
      labels:
        app: {{.Name}}
    spec:
      securityContext:
        runAsUser: {{.RunAsUser}}
        runAsGroup: {{.RunAsGroup}}
        fsGroup: {{.FsGroup}}
      initContainers:
        - name: init-dirs
          image: busybox
          command: ["sh", "-c", "mkdir -p /mnt/home /mnt/data"]
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
          volumeMounts:
            - name: user-data
              mountPath: /mnt/home
              subPath: "workspaces/{{.Name}}/home"
            - name: user-data
              mountPath: /mnt/data
              subPath: "workspaces/{{.Name}}/data"
      containers:
        - name: {{.Name}}
          image: codercom/code-server:4.91.1
          args: 
          - "--auth"
          - "none"
          - "--bind-addr"
          - "0.0.0.0:8080"
          - "--disable-telemetry"
          - "--disable-update-check"
          - "/data"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: {{.CPURequest}}
              memory: {{.MemRequest}}
            limits:
              cpu: {{.CPULimit}}
              memory: {{.MemLimit}}
          volumeMounts:
            - name: user-data
              mountPath: /home/coder
              subPath: "workspaces/{{.Name}}/home"
            - name: user-data
              mountPath: /data
              subPath: "workspaces/{{.Name}}/data"
      volumes:
        - name: user-data
          persistentVolumeClaim:
            claimName: shared-storage-pvc