// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: workspace.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkspaceStatus int32

const (
	WorkspaceStatus_WORKSPACE_STATUS_UNSPECIFIED  WorkspaceStatus = 0
	WorkspaceStatus_WORKSPACE_STATUS_PROVISIONING WorkspaceStatus = 1
	WorkspaceStatus_WORKSPACE_STATUS_RUNNING      WorkspaceStatus = 2
	WorkspaceStatus_WORKSPACE_STATUS_DELETING     WorkspaceStatus = 3
	WorkspaceStatus_WORKSPACE_STATUS_STOPPED      WorkspaceStatus = 4
	WorkspaceStatus_WORKSPACE_STATUS_FAILED       WorkspaceStatus = 5
)

// Enum value maps for WorkspaceStatus.
var (
	WorkspaceStatus_name = map[int32]string{
		0: "WORKSPACE_STATUS_UNSPECIFIED",
		1: "WORKSPACE_STATUS_PROVISIONING",
		2: "WORKSPACE_STATUS_RUNNING",
		3: "WORKSPACE_STATUS_DELETING",
		4: "WORKSPACE_STATUS_STOPPED",
		5: "WORKSPACE_STATUS_FAILED",
	}
	WorkspaceStatus_value = map[string]int32{
		"WORKSPACE_STATUS_UNSPECIFIED":  0,
		"WORKSPACE_STATUS_PROVISIONING": 1,
		"WORKSPACE_STATUS_RUNNING":      2,
		"WORKSPACE_STATUS_DELETING":     3,
		"WORKSPACE_STATUS_STOPPED":      4,
		"WORKSPACE_STATUS_FAILED":       5,
	}
)

func (x WorkspaceStatus) Enum() *WorkspaceStatus {
	p := new(WorkspaceStatus)
	*p = x
	return p
}

func (x WorkspaceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkspaceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_workspace_proto_enumTypes[0].Descriptor()
}

func (WorkspaceStatus) Type() protoreflect.EnumType {
	return &file_workspace_proto_enumTypes[0]
}

func (x WorkspaceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkspaceStatus.Descriptor instead.
func (WorkspaceStatus) EnumDescriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{0}
}

type ResourceSpec struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CpuRequest          string                 `protobuf:"bytes,1,opt,name=cpu_request,json=cpuRequest,proto3" json:"cpu_request,omitempty"`
	CpuLimit            string                 `protobuf:"bytes,2,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	MemoryRequest       string                 `protobuf:"bytes,3,opt,name=memory_request,json=memoryRequest,proto3" json:"memory_request,omitempty"`
	MemoryLimit         string                 `protobuf:"bytes,4,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	StorageRequest      string                 `protobuf:"bytes,5,opt,name=storage_request,json=storageRequest,proto3" json:"storage_request,omitempty"`
	StorageLimit        string                 `protobuf:"bytes,6,opt,name=storage_limit,json=storageLimit,proto3" json:"storage_limit,omitempty"`
	CpuTerminalLimit    string                 `protobuf:"bytes,7,opt,name=cpu_terminal_limit,json=cpuTerminalLimit,proto3" json:"cpu_terminal_limit,omitempty"`
	MemoryTerminalLimit string                 `protobuf:"bytes,8,opt,name=memory_terminal_limit,json=memoryTerminalLimit,proto3" json:"memory_terminal_limit,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResourceSpec) Reset() {
	*x = ResourceSpec{}
	mi := &file_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSpec) ProtoMessage() {}

func (x *ResourceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSpec.ProtoReflect.Descriptor instead.
func (*ResourceSpec) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceSpec) GetCpuRequest() string {
	if x != nil {
		return x.CpuRequest
	}
	return ""
}

func (x *ResourceSpec) GetCpuLimit() string {
	if x != nil {
		return x.CpuLimit
	}
	return ""
}

func (x *ResourceSpec) GetMemoryRequest() string {
	if x != nil {
		return x.MemoryRequest
	}
	return ""
}

func (x *ResourceSpec) GetMemoryLimit() string {
	if x != nil {
		return x.MemoryLimit
	}
	return ""
}

func (x *ResourceSpec) GetStorageRequest() string {
	if x != nil {
		return x.StorageRequest
	}
	return ""
}

func (x *ResourceSpec) GetStorageLimit() string {
	if x != nil {
		return x.StorageLimit
	}
	return ""
}

func (x *ResourceSpec) GetCpuTerminalLimit() string {
	if x != nil {
		return x.CpuTerminalLimit
	}
	return ""
}

func (x *ResourceSpec) GetMemoryTerminalLimit() string {
	if x != nil {
		return x.MemoryTerminalLimit
	}
	return ""
}

type CreatePort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	WorkspaceName string                 `protobuf:"bytes,3,opt,name=workspace_name,json=workspaceName,proto3" json:"workspace_name,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,5,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePort) Reset() {
	*x = CreatePort{}
	mi := &file_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePort) ProtoMessage() {}

func (x *CreatePort) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePort.ProtoReflect.Descriptor instead.
func (*CreatePort) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePort) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CreatePort) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CreatePort) GetWorkspaceName() string {
	if x != nil {
		return x.WorkspaceName
	}
	return ""
}

func (x *CreatePort) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePort) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type DeletePort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	WorkspaceName string                 `protobuf:"bytes,2,opt,name=workspace_name,json=workspaceName,proto3" json:"workspace_name,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePort) Reset() {
	*x = DeletePort{}
	mi := &file_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePort) ProtoMessage() {}

func (x *DeletePort) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePort.ProtoReflect.Descriptor instead.
func (*DeletePort) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{2}
}

func (x *DeletePort) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DeletePort) GetWorkspaceName() string {
	if x != nil {
		return x.WorkspaceName
	}
	return ""
}

func (x *DeletePort) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type WorkspaceIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceIdentity) Reset() {
	*x = WorkspaceIdentity{}
	mi := &file_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceIdentity) ProtoMessage() {}

func (x *WorkspaceIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceIdentity.ProtoReflect.Descriptor instead.
func (*WorkspaceIdentity) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{3}
}

func (x *WorkspaceIdentity) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *WorkspaceIdentity) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WorkspaceIdentity) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *WorkspaceIdentity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkspaceIdentity) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WorkspaceIdentity) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateWorkspaceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *WorkspaceIdentity     `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Resources     *ResourceSpec          `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"`
	EnvVars       map[string]string      `protobuf:"bytes,4,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timezone      string                 `protobuf:"bytes,5,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Replicas      int32                  `protobuf:"varint,6,opt,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkspaceEvent) Reset() {
	*x = CreateWorkspaceEvent{}
	mi := &file_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkspaceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceEvent) ProtoMessage() {}

func (x *CreateWorkspaceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceEvent.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceEvent) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWorkspaceEvent) GetIdentity() *WorkspaceIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *CreateWorkspaceEvent) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CreateWorkspaceEvent) GetResources() *ResourceSpec {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *CreateWorkspaceEvent) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *CreateWorkspaceEvent) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *CreateWorkspaceEvent) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

type AddonSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	DbUser        string                 `protobuf:"bytes,2,opt,name=db_user,json=dbUser,proto3" json:"db_user,omitempty"`
	DbPassword    string                 `protobuf:"bytes,3,opt,name=db_password,json=dbPassword,proto3" json:"db_password,omitempty"`
	DbName        string                 `protobuf:"bytes,4,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddonSpec) Reset() {
	*x = AddonSpec{}
	mi := &file_workspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddonSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddonSpec) ProtoMessage() {}

func (x *AddonSpec) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddonSpec.ProtoReflect.Descriptor instead.
func (*AddonSpec) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{5}
}

func (x *AddonSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *AddonSpec) GetDbUser() string {
	if x != nil {
		return x.DbUser
	}
	return ""
}

func (x *AddonSpec) GetDbPassword() string {
	if x != nil {
		return x.DbPassword
	}
	return ""
}

func (x *AddonSpec) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

type AddPodEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *WorkspaceIdentity     `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Resources     *ResourceSpec          `protobuf:"bytes,4,opt,name=resources,proto3" json:"resources,omitempty"`
	Replicas      int32                  `protobuf:"varint,5,opt,name=replicas,proto3" json:"replicas,omitempty"`
	AddOns        *AddonSpec             `protobuf:"bytes,6,opt,name=add_ons,json=addOns,proto3" json:"add_ons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPodEvent) Reset() {
	*x = AddPodEvent{}
	mi := &file_workspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPodEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPodEvent) ProtoMessage() {}

func (x *AddPodEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPodEvent.ProtoReflect.Descriptor instead.
func (*AddPodEvent) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{6}
}

func (x *AddPodEvent) GetIdentity() *WorkspaceIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *AddPodEvent) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *AddPodEvent) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *AddPodEvent) GetResources() *ResourceSpec {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *AddPodEvent) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *AddPodEvent) GetAddOns() *AddonSpec {
	if x != nil {
		return x.AddOns
	}
	return nil
}

type DeleteWorkspaceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *WorkspaceIdentity     `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceEvent) Reset() {
	*x = DeleteWorkspaceEvent{}
	mi := &file_workspace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceEvent) ProtoMessage() {}

func (x *DeleteWorkspaceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceEvent.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceEvent) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteWorkspaceEvent) GetIdentity() *WorkspaceIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type StopWorkspaceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *WorkspaceIdentity     `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopWorkspaceEvent) Reset() {
	*x = StopWorkspaceEvent{}
	mi := &file_workspace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopWorkspaceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWorkspaceEvent) ProtoMessage() {}

func (x *StopWorkspaceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWorkspaceEvent.ProtoReflect.Descriptor instead.
func (*StopWorkspaceEvent) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{8}
}

func (x *StopWorkspaceEvent) GetIdentity() *WorkspaceIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type StartWorkspaceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *WorkspaceIdentity     `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkspaceEvent) Reset() {
	*x = StartWorkspaceEvent{}
	mi := &file_workspace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkspaceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkspaceEvent) ProtoMessage() {}

func (x *StartWorkspaceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkspaceEvent.ProtoReflect.Descriptor instead.
func (*StartWorkspaceEvent) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{9}
}

func (x *StartWorkspaceEvent) GetIdentity() *WorkspaceIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type UpdateStatusEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Status        WorkspaceStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=workspace.v1.WorkspaceStatus" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusEvent) Reset() {
	*x = UpdateStatusEvent{}
	mi := &file_workspace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusEvent) ProtoMessage() {}

func (x *UpdateStatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusEvent.ProtoReflect.Descriptor instead.
func (*UpdateStatusEvent) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateStatusEvent) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *UpdateStatusEvent) GetStatus() WorkspaceStatus {
	if x != nil {
		return x.Status
	}
	return WorkspaceStatus_WORKSPACE_STATUS_UNSPECIFIED
}

func (x *UpdateStatusEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpdateStatusEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type WorkspaceEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkspaceEnvelope_Create
	//	*WorkspaceEnvelope_Add
	//	*WorkspaceEnvelope_Delete
	//	*WorkspaceEnvelope_Stop
	//	*WorkspaceEnvelope_Start
	//	*WorkspaceEnvelope_Update
	//	*WorkspaceEnvelope_CreatePort
	//	*WorkspaceEnvelope_DeletePort
	Payload       isWorkspaceEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceEnvelope) Reset() {
	*x = WorkspaceEnvelope{}
	mi := &file_workspace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceEnvelope) ProtoMessage() {}

func (x *WorkspaceEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceEnvelope.ProtoReflect.Descriptor instead.
func (*WorkspaceEnvelope) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{11}
}

func (x *WorkspaceEnvelope) GetPayload() isWorkspaceEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkspaceEnvelope) GetCreate() *CreateWorkspaceEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorkspaceEnvelope_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *WorkspaceEnvelope) GetAdd() *AddPodEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorkspaceEnvelope_Add); ok {
			return x.Add
		}
	}
	return nil
}

func (x *WorkspaceEnvelope) GetDelete() *DeleteWorkspaceEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorkspaceEnvelope_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *WorkspaceEnvelope) GetStop() *StopWorkspaceEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorkspaceEnvelope_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *WorkspaceEnvelope) GetStart() *StartWorkspaceEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorkspaceEnvelope_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *WorkspaceEnvelope) GetUpdate() *UpdateStatusEvent {
	if x != nil {
		if x, ok := x.Payload.(*WorkspaceEnvelope_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *WorkspaceEnvelope) GetCreatePort() *CreatePort {
	if x != nil {
		if x, ok := x.Payload.(*WorkspaceEnvelope_CreatePort); ok {
			return x.CreatePort
		}
	}
	return nil
}

func (x *WorkspaceEnvelope) GetDeletePort() *DeletePort {
	if x != nil {
		if x, ok := x.Payload.(*WorkspaceEnvelope_DeletePort); ok {
			return x.DeletePort
		}
	}
	return nil
}

type isWorkspaceEnvelope_Payload interface {
	isWorkspaceEnvelope_Payload()
}

type WorkspaceEnvelope_Create struct {
	Create *CreateWorkspaceEvent `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type WorkspaceEnvelope_Add struct {
	Add *AddPodEvent `protobuf:"bytes,2,opt,name=add,proto3,oneof"`
}

type WorkspaceEnvelope_Delete struct {
	Delete *DeleteWorkspaceEvent `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

type WorkspaceEnvelope_Stop struct {
	Stop *StopWorkspaceEvent `protobuf:"bytes,4,opt,name=stop,proto3,oneof"`
}

type WorkspaceEnvelope_Start struct {
	Start *StartWorkspaceEvent `protobuf:"bytes,5,opt,name=start,proto3,oneof"`
}

type WorkspaceEnvelope_Update struct {
	Update *UpdateStatusEvent `protobuf:"bytes,6,opt,name=update,proto3,oneof"`
}

type WorkspaceEnvelope_CreatePort struct {
	CreatePort *CreatePort `protobuf:"bytes,7,opt,name=create_port,json=createPort,proto3,oneof"`
}

type WorkspaceEnvelope_DeletePort struct {
	DeletePort *DeletePort `protobuf:"bytes,8,opt,name=delete_port,json=deletePort,proto3,oneof"`
}

func (*WorkspaceEnvelope_Create) isWorkspaceEnvelope_Payload() {}

func (*WorkspaceEnvelope_Add) isWorkspaceEnvelope_Payload() {}

func (*WorkspaceEnvelope_Delete) isWorkspaceEnvelope_Payload() {}

func (*WorkspaceEnvelope_Stop) isWorkspaceEnvelope_Payload() {}

func (*WorkspaceEnvelope_Start) isWorkspaceEnvelope_Payload() {}

func (*WorkspaceEnvelope_Update) isWorkspaceEnvelope_Payload() {}

func (*WorkspaceEnvelope_CreatePort) isWorkspaceEnvelope_Payload() {}

func (*WorkspaceEnvelope_DeletePort) isWorkspaceEnvelope_Payload() {}

var File_workspace_proto protoreflect.FileDescriptor

const file_workspace_proto_rawDesc = "" +
	"\n" +
	"\x0fworkspace.proto\x12\fworkspace.v1\"\xc6\x02\n" +
	"\fResourceSpec\x12\x1f\n" +
	"\vcpu_request\x18\x01 \x01(\tR\n" +
	"cpuRequest\x12\x1b\n" +
	"\tcpu_limit\x18\x02 \x01(\tR\bcpuLimit\x12%\n" +
	"\x0ememory_request\x18\x03 \x01(\tR\rmemoryRequest\x12!\n" +
	"\fmemory_limit\x18\x04 \x01(\tR\vmemoryLimit\x12'\n" +
	"\x0fstorage_request\x18\x05 \x01(\tR\x0estorageRequest\x12#\n" +
	"\rstorage_limit\x18\x06 \x01(\tR\fstorageLimit\x12,\n" +
	"\x12cpu_terminal_limit\x18\a \x01(\tR\x10cpuTerminalLimit\x122\n" +
	"\x15memory_terminal_limit\x18\b \x01(\tR\x13memoryTerminalLimit\"\x9b\x01\n" +
	"\n" +
	"CreatePort\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12%\n" +
	"\x0eworkspace_name\x18\x03 \x01(\tR\rworkspaceName\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12!\n" +
	"\fworkspace_id\x18\x05 \x01(\tR\vworkspaceId\"`\n" +
	"\n" +
	"DeletePort\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12%\n" +
	"\x0eworkspace_name\x18\x02 \x01(\tR\rworkspaceName\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\xb9\x01\n" +
	"\x11WorkspaceIdentity\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\"\xee\x02\n" +
	"\x14CreateWorkspaceEvent\x12;\n" +
	"\bidentity\x18\x01 \x01(\v2\x1f.workspace.v1.WorkspaceIdentityR\bidentity\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x128\n" +
	"\tresources\x18\x03 \x01(\v2\x1a.workspace.v1.ResourceSpecR\tresources\x12J\n" +
	"\benv_vars\x18\x04 \x03(\v2/.workspace.v1.CreateWorkspaceEvent.EnvVarsEntryR\aenvVars\x12\x1a\n" +
	"\btimezone\x18\x05 \x01(\tR\btimezone\x12\x1a\n" +
	"\breplicas\x18\x06 \x01(\x05R\breplicas\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\tAddonSpec\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x17\n" +
	"\adb_user\x18\x02 \x01(\tR\x06dbUser\x12\x1f\n" +
	"\vdb_password\x18\x03 \x01(\tR\n" +
	"dbPassword\x12\x17\n" +
	"\adb_name\x18\x04 \x01(\tR\x06dbName\"\x89\x02\n" +
	"\vAddPodEvent\x12;\n" +
	"\bidentity\x18\x01 \x01(\v2\x1f.workspace.v1.WorkspaceIdentityR\bidentity\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x128\n" +
	"\tresources\x18\x04 \x01(\v2\x1a.workspace.v1.ResourceSpecR\tresources\x12\x1a\n" +
	"\breplicas\x18\x05 \x01(\x05R\breplicas\x120\n" +
	"\aadd_ons\x18\x06 \x01(\v2\x17.workspace.v1.AddonSpecR\x06addOns\"S\n" +
	"\x14DeleteWorkspaceEvent\x12;\n" +
	"\bidentity\x18\x01 \x01(\v2\x1f.workspace.v1.WorkspaceIdentityR\bidentity\"Q\n" +
	"\x12StopWorkspaceEvent\x12;\n" +
	"\bidentity\x18\x01 \x01(\v2\x1f.workspace.v1.WorkspaceIdentityR\bidentity\"R\n" +
	"\x13StartWorkspaceEvent\x12;\n" +
	"\bidentity\x18\x01 \x01(\v2\x1f.workspace.v1.WorkspaceIdentityR\bidentity\"\x9e\x01\n" +
	"\x11UpdateStatusEvent\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.workspace.v1.WorkspaceStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"\xf1\x03\n" +
	"\x11WorkspaceEnvelope\x12<\n" +
	"\x06create\x18\x01 \x01(\v2\".workspace.v1.CreateWorkspaceEventH\x00R\x06create\x12-\n" +
	"\x03add\x18\x02 \x01(\v2\x19.workspace.v1.AddPodEventH\x00R\x03add\x12<\n" +
	"\x06delete\x18\x03 \x01(\v2\".workspace.v1.DeleteWorkspaceEventH\x00R\x06delete\x126\n" +
	"\x04stop\x18\x04 \x01(\v2 .workspace.v1.StopWorkspaceEventH\x00R\x04stop\x129\n" +
	"\x05start\x18\x05 \x01(\v2!.workspace.v1.StartWorkspaceEventH\x00R\x05start\x129\n" +
	"\x06update\x18\x06 \x01(\v2\x1f.workspace.v1.UpdateStatusEventH\x00R\x06update\x12;\n" +
	"\vcreate_port\x18\a \x01(\v2\x18.workspace.v1.CreatePortH\x00R\n" +
	"createPort\x12;\n" +
	"\vdelete_port\x18\b \x01(\v2\x18.workspace.v1.DeletePortH\x00R\n" +
	"deletePortB\t\n" +
	"\apayload*\xce\x01\n" +
	"\x0fWorkspaceStatus\x12 \n" +
	"\x1cWORKSPACE_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dWORKSPACE_STATUS_PROVISIONING\x10\x01\x12\x1c\n" +
	"\x18WORKSPACE_STATUS_RUNNING\x10\x02\x12\x1d\n" +
	"\x19WORKSPACE_STATUS_DELETING\x10\x03\x12\x1c\n" +
	"\x18WORKSPACE_STATUS_STOPPED\x10\x04\x12\x1b\n" +
	"\x17WORKSPACE_STATUS_FAILED\x10\x05B/Z-github.com/wafi11/workspaces/gen/workspace/v1b\x06proto3"

var (
	file_workspace_proto_rawDescOnce sync.Once
	file_workspace_proto_rawDescData []byte
)

func file_workspace_proto_rawDescGZIP() []byte {
	file_workspace_proto_rawDescOnce.Do(func() {
		file_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workspace_proto_rawDesc), len(file_workspace_proto_rawDesc)))
	})
	return file_workspace_proto_rawDescData
}

var file_workspace_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_workspace_proto_goTypes = []any{
	(WorkspaceStatus)(0),         // 0: workspace.v1.WorkspaceStatus
	(*ResourceSpec)(nil),         // 1: workspace.v1.ResourceSpec
	(*CreatePort)(nil),           // 2: workspace.v1.CreatePort
	(*DeletePort)(nil),           // 3: workspace.v1.DeletePort
	(*WorkspaceIdentity)(nil),    // 4: workspace.v1.WorkspaceIdentity
	(*CreateWorkspaceEvent)(nil), // 5: workspace.v1.CreateWorkspaceEvent
	(*AddonSpec)(nil),            // 6: workspace.v1.AddonSpec
	(*AddPodEvent)(nil),          // 7: workspace.v1.AddPodEvent
	(*DeleteWorkspaceEvent)(nil), // 8: workspace.v1.DeleteWorkspaceEvent
	(*StopWorkspaceEvent)(nil),   // 9: workspace.v1.StopWorkspaceEvent
	(*StartWorkspaceEvent)(nil),  // 10: workspace.v1.StartWorkspaceEvent
	(*UpdateStatusEvent)(nil),    // 11: workspace.v1.UpdateStatusEvent
	(*WorkspaceEnvelope)(nil),    // 12: workspace.v1.WorkspaceEnvelope
	nil,                          // 13: workspace.v1.CreateWorkspaceEvent.EnvVarsEntry
}
var file_workspace_proto_depIdxs = []int32{
	4,  // 0: workspace.v1.CreateWorkspaceEvent.identity:type_name -> workspace.v1.WorkspaceIdentity
	1,  // 1: workspace.v1.CreateWorkspaceEvent.resources:type_name -> workspace.v1.ResourceSpec
	13, // 2: workspace.v1.CreateWorkspaceEvent.env_vars:type_name -> workspace.v1.CreateWorkspaceEvent.EnvVarsEntry
	4,  // 3: workspace.v1.AddPodEvent.identity:type_name -> workspace.v1.WorkspaceIdentity
	1,  // 4: workspace.v1.AddPodEvent.resources:type_name -> workspace.v1.ResourceSpec
	6,  // 5: workspace.v1.AddPodEvent.add_ons:type_name -> workspace.v1.AddonSpec
	4,  // 6: workspace.v1.DeleteWorkspaceEvent.identity:type_name -> workspace.v1.WorkspaceIdentity
	4,  // 7: workspace.v1.StopWorkspaceEvent.identity:type_name -> workspace.v1.WorkspaceIdentity
	4,  // 8: workspace.v1.StartWorkspaceEvent.identity:type_name -> workspace.v1.WorkspaceIdentity
	0,  // 9: workspace.v1.UpdateStatusEvent.status:type_name -> workspace.v1.WorkspaceStatus
	5,  // 10: workspace.v1.WorkspaceEnvelope.create:type_name -> workspace.v1.CreateWorkspaceEvent
	7,  // 11: workspace.v1.WorkspaceEnvelope.add:type_name -> workspace.v1.AddPodEvent
	8,  // 12: workspace.v1.WorkspaceEnvelope.delete:type_name -> workspace.v1.DeleteWorkspaceEvent
	9,  // 13: workspace.v1.WorkspaceEnvelope.stop:type_name -> workspace.v1.StopWorkspaceEvent
	10, // 14: workspace.v1.WorkspaceEnvelope.start:type_name -> workspace.v1.StartWorkspaceEvent
	11, // 15: workspace.v1.WorkspaceEnvelope.update:type_name -> workspace.v1.UpdateStatusEvent
	2,  // 16: workspace.v1.WorkspaceEnvelope.create_port:type_name -> workspace.v1.CreatePort
	3,  // 17: workspace.v1.WorkspaceEnvelope.delete_port:type_name -> workspace.v1.DeletePort
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_workspace_proto_init() }
func file_workspace_proto_init() {
	if File_workspace_proto != nil {
		return
	}
	file_workspace_proto_msgTypes[11].OneofWrappers = []any{
		(*WorkspaceEnvelope_Create)(nil),
		(*WorkspaceEnvelope_Add)(nil),
		(*WorkspaceEnvelope_Delete)(nil),
		(*WorkspaceEnvelope_Stop)(nil),
		(*WorkspaceEnvelope_Start)(nil),
		(*WorkspaceEnvelope_Update)(nil),
		(*WorkspaceEnvelope_CreatePort)(nil),
		(*WorkspaceEnvelope_DeletePort)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workspace_proto_rawDesc), len(file_workspace_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workspace_proto_goTypes,
		DependencyIndexes: file_workspace_proto_depIdxs,
		EnumInfos:         file_workspace_proto_enumTypes,
		MessageInfos:      file_workspace_proto_msgTypes,
	}.Build()
	File_workspace_proto = out.File
	file_workspace_proto_goTypes = nil
	file_workspace_proto_depIdxs = nil
}
