apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      app: {{.Name}}
  template:
    metadata:
      labels:
        app: {{.Name}}
    spec:
      securityContext:
        runAsUser: 70
        runAsGroup: 70
        fsGroup: 70
      initContainers:
        - name: init-pgdata
          image: busybox
          securityContext:
            runAsUser: 0
          command: ["sh", "-c", "mkdir -p /mnt/postgres/pgdata/data && chmod 700 /mnt/postgres/pgdata/data && chown -R 70:70 /mnt/postgres"]
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
          volumeMounts:
            - name: user-data
              mountPath: /mnt
      containers:
        - name: {{.Name}}
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              value: {{.DB_USER}}
            - name: POSTGRES_PASSWORD
              value: {{.DB_PASSWORD}}
            - name: POSTGRES_DB
              value: {{.DB_NAME}}
            - name: PGDATA
              value: /data/pgdata/data
          resources:
            requests:
              cpu: {{.CPURequest}}
              memory: {{.MemRequest}}
            limits:
              cpu: {{.CPULimit}}
              memory: {{.MemLimit}}
          volumeMounts:
            - name: user-data
              mountPath: /data
              subPath: postgres
      volumes:
        - name: user-data
          persistentVolumeClaim:
            claimName: shared-storage-pvc