@BASE_URL = http://localhost:8080/api/v1
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYzYzNDg3ZDMtOTcxNi00YmM4LTkyZWMtZjQzZjc3ZGQ0MjY3IiwidXNlcm5hbWUiOiJhZG1pbiIsInN1YiI6ImM2MzQ4N2QzLTk3MTYtNGJjOC05MmVjLWY0M2Y3N2RkNDI2NyIsImV4cCI6MTc3NjE0MDM5MCwiaWF0IjoxNzc2MTM2NzkwfQ.8SX62mUALWKBFG47rSOjhdx1IT5fDRFeUbI8GO7QEJY


###
POST {{BASE_URL}}/workspaces
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "name": "development",
    "password" : "password123",
    "template_id" : "a347008b-cf85-4f8c-b92b-7fed81e37aae",
    "limit_ram_mb" : 1024,
    "limit_cpu_cores" : 1.0,
    "req_ram_mb" : 512,
    "req_cpu_cores" : 0.5
}

###
POST {{BASE_URL}}/workspaces
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "name": "postgres",
    "password" : "password123",
    "template_id" : "8448f577-a307-417c-b632-fb2b71ff5766",
    "limit_ram_mb" : 1024,
    "limit_cpu_cores" : 1.0,
    "req_ram_mb" : 512,
    "req_cpu_cores" : 0.5,
    "env_vars" : {
        "DB_NAME" : "development",
        "DB_PASSWORD" : "development",
        "DB_USER" : "development"
    }
}