apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terminal-pvc
  namespace: { { .Namespace } }
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: {{ .StorageSize }}
