apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: terminal
  namespace: {{.Namespace}}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/websocket-services: "terminal"
    nginx.ingress.kubernetes.io/upgrade-type: "websocket"
    nginx.ingress.kubernetes.io/auth-url: "http://platform-service.default.svc.cluster.local:8080/api/v1/auth/validate"
    nginx.ingress.kubernetes.io/auth-signin: "https://api.wfdnstore.online/api/v1/auth/login?rd=https://$host$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-User"
spec:
  ingressClassName: nginx
  rules:
  - host: "{{.Name}}.{{.Domain}}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: terminal
            port:
              number: 80
