apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminal
  namespace: {{.Namespace}}
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      app: terminal
  template:
    metadata:
      labels:
        app: terminal
    spec:
      securityContext:
        runAsUser: {{.RunAsUser}}
        runAsGroup: {{.RunAsGroup}}
        fsGroup: {{.FsGroup}}
        runAsNonRoot: true
      containers:
        - name: terminal
          image: 192.168.1.31:5050/workspaces/workspace-terminal:latest
          env:
          - name: WS_TOKEN
            value: "{{.WS_TOKEN}}"
          - name: WS_REFRESH_TOKEN
            value: "{{.WS_REFRESH_TOKEN}}"
          - name: WS_API_URL
            value: "{{.WS_API_URL}}"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 7681
          command:
            - ttyd
            - -W
            - -p
            - "7681"
            - /bin/bash
            - -c
            - |
              export PS1='\[\033[01;32m\]{{.Username}}@kubespace\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
              cd /data
              exec /bin/bash --login
          resources:
            requests:
              cpu: "100m"         
              memory: "128Mi"    
            limits:
              cpu: "500m"         
              memory: "512Mi"     
          volumeMounts:
            - name: user-data
              mountPath: /data
              subPath: home
      volumes:
        - name: user-data
          persistentVolumeClaim:
            claimName: shared-storage-pvc